from vkbottle import BaseStateGroup


class MyStates(BaseStateGroup):
    WAITING_FOR_ONBOARDING_DATA = "waiting_for_onboarding_data"
    WAITING_CONFIRM_DATA = "waiting_confirm_data"
    WAITING_FOR_DATE = "waiting_for_date"
    WAITING_FOR_TIME = "waiting_for_time"
    WAITING_FOR_CITY = "waiting_for_city"
    WAITING_SYNASTRY_DATE = "waiting_synastry_date"
    WAITING_SYNASTRY_TIME = "waiting_synastry_time"
    WAITING_SYNASTRY_CITY = "waiting_synastry_city"
    WAITING_ORACLE_QUESTION = "waiting_oracle_question"
    WAITING_SUPPORT_QUESTION = "waiting_support_question"
    ORACLE_CUT = "oracle_cut"
    ORACLE_DRAW = "oracle_draw"
    GLOBAL_CUT = "global_cut"
    WAITING_RESET_CONFIRM = "waiting_reset_confirm"
    WAITING_PALMISTRY_PHOTOS = "waiting_palmistry_photos"
    WAITING_SYNASTRY_NAME = "waiting_synastry_name"
    WAITING_FEEDBACK_COMMENT = "waiting_feedback_comment"
    WAITING_OCULOMANCY_PHOTO = "waiting_oculomancy_photo"
    WAITING_SIGIL_WISH = "waiting_sigil_wish"
    WAITING_GEO_LOCATION = "waiting_geo_location"
    WAITING_TOTEM_STEP1 = "waiting_totem_step1"
    WAITING_TOTEM_STEP2 = "waiting_totem_step2"
    WAITING_KARMA_STEP1 = "waiting_karma_step1"
    WAITING_KARMA_STEP2 = "waiting_karma_step2"
    WAITING_DREAM_TEXT = "waiting_dream_text"
