services:
  - type: web
    name: vkbot
    env: python
    plan: starter
    pythonVersion: "3.12"
    buildCommand: pip install -r requirements.txt
    startCommand: python -u main.py
    envVars:
      - key: WEASYPRINT_NO_FONTS
        value: 1
      - key: PORT
        value: 10000
    healthCheckPath: /
